spring:
  profiles:
    group:
      local: "local,common"
---
spring:
  profiles:
    group:
      kimjaehee: "kimjaehee,common"
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.naver.com
    port: 465
    username: rlawogml_18@naver.com
    password: 262EPFVE1C9C
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
    protocol: smtps
server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---
spring:
  config:
    activate:
      on-profile: kimjaehee
  datasource:
    hikari:
      dbType: MYSQL
      username: root
      dbPort: 3306
      dbIp: 192.168.0.5
      password: 1234
      jdbc-url: jdbc:mysql://192.168.0.5:3306/book?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      connectionTimeout: 40000
      serverTimezone: Asia/Seoul
      auto-commit: true
      maximumPoolSize: 5
      maxLifetime: 35000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---